#!/bin/zsh
# Check if an argument is provided
if [ "$#" -ne 1 ]; then
	echo "Usage: vimtab <file>"
	exit 1
fi

# Store the file path in a variable
FILEPATH="$1"
CWD="$PWD"

# AppleScript to open vim in a new iTerm tab with the file
osascript <<EOF
tell application "iTerm"
	activate
	try
		set newWindow to (create window with default profile)
		on error
			tell current session of current window
				write text "cd '$CWD' && vim '$FILEPATH' && exit"
			end tell
	end try
	tell current session of newWindow
		write text "cd '$CWD' && vim '$FILEPATH' && exit"
	end tell
end tell
EOF
